ai_providers:
  anthropic:
    api_key: ${ANTHROPIC_API_KEY}
    enabled: false
    max_tokens: 1000
    model: claude-3-haiku-20240307
    temperature: 0.3
  default: replicate
  gemini:
    api_key: ${GEMINI_API_KEY}
    enabled: false
    max_tokens: 1000
    model: gemini-pro
    temperature: 0.3
  openai:
    api_key: ${OPENAI_API_KEY}
    enabled: false
    max_tokens: 1000
    model: gpt-3.5-turbo
    temperature: 0.3
  replicate:
    api_token: ${REPLICATE_API_TOKEN}
    enabled: true
    max_tokens: 2000
    model: meta/llama-2-70b-chat
    repetition_penalty: 1.1
    temperature: 0.3
    top_p: 0.9
fallback:
  enabled: true
  order:
  - replicate
  - openai
  - gemini
  - anthropic
